### PR TITLE
A few build and git improvements

### PR DESCRIPTION
**Pull request by mikey**
Added a bunch of build and git improvements:

c7c6210 Update gitignore with more build files
c84a400 makefile: Make default build target all
0966671 makefile: bin depends on lib
503615d makefile: Make default TOPDIR something usable

### CODE REVIEW

**Comment by mehuljpatel** [comment]
Hi Mikey, Setting TOPDIR to PWD does not help unless you are always building from topmost dir.

**Comment by mikey** [comment]
To build currently you *have to* modify TOPDIR.  This just provides a sane default for people who want to compile out of the box. 

So if you want to build outside of PWD you had to change TOPDIR before now and after.  It seems to me like this is just the same before and after.  This just gives you a sane default.

**Comment by thejta** [comment]
I agree having a sane default would be good, or at least putting an error in place if TOPDIR isn't by the user in the env before calling make.

**Comment by mehuljpatel** [comment]
Hi Mikey, setting TOPDIR to ${PWD} breaks, when lets say, you do a complete build from TOPDIR and then go to a specific exerciser directory and then make some changes and build at that level itself. Since it only includes htx.mk, include path goes for toss and compilation fails.
Does that make sense ?

**Comment by thejta** [comment]
Mehul - I understand your issue.  eCMD does something similar with including a common makefile.  MAKEBASE in CMD is the same as your TOPDIR.  We used the logic below to figure out where that top level makefile is located:

MAKEBASE_PATH := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

https://github.com/open-power/eCMD/blob/master-next/makefile.base

**Comment by mikey** [comment]
Thanks Jason, I've repushed with that as the update.  Does this work for you Mehul?

**Comment by mehuljpatel** [comment]
Cool. That works. Thanks Mikey and Jason. HTX is already reaping benefits of being open :)

**Pull request merged**
