### PR TITLE
Adding hours to get_run_time output

### PR DESCRIPTION
**Pull request by narasimhan-v**
Adding hours to get_run_time output, which is just minutes and
seconds as of now.

Signed-off-by: Narasimhan V <sim@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by avinashkuttan** [comment]
This code change causes the command output format change. 
The command output change may causes failure of the existing test automation, since the automation scripts process the HTX command output.
So, the existing command output format change requires automation update also. 
Since this is not a critical change, the code update is avoiding now.

**Comment by narasimhan-v** [comment]
@avinashkuttan Is there too much dependency on the output format ?
The reason I wanted this change is, when we run HTX for more than couple of hours (for days together sometimes) it is difficult to interpret only minutes. It helps if the output is in hours. Going by the same logic, output in terms of days would be even better.

**Comment by narasimhan-v** [comment]
@avinashkuttan Please let me know, if the automated tests are part of HTX, I can change them also.

Also, there is a fixup of this code change, which I will do if you are fine with accepting it.

**Comment by avinashkuttan** [comment]
@narasimhan-v Different labs use the HTX command line interface for their test automation. We do not have access to the automation scripts. If we make any command output change, that may affect the existing automation. So we avoid the output format change as much as possible. 
In this case, since the time value is available in minutes, you can converts at your end to the required format and use it.

**Comment by narasimhan-v** [comment]
@avinashkuttan okay, thanks.

**Pull request closed without merging**
