### PR TITLE
Fix bad shifts in framework.c

### PR DESCRIPTION
**Pull request by antonblanchard**
The clang undefined behaviour sanitizer found a number of places where
we left shift out of an int. An example:

../hxefpu64/framework.c:6734:10: runtime error: left shift of 62 by 26 places cannot be represented in type 'int'
SUMMARY: AddressSanitizer: undefined-behavior ../hxefpu64/framework.c:6734:10 in

Fix this by making the constants unsigned long.

Signed-off-by: Anton Blanchard <anton@samba.org>

### CODE REVIEW

**Comment by kalok1504** [comment]
left shift of opcode oe extended opcode values e.g (62 << 26 = 0xF8000000) are as per ppc instruction set architecture. probably we need to work towards code safety in case mistake in hand coding of instructions. we could typecast to long and assert if bits spills left over 32 bits. Changes in macro can have impact on instruction build routines as well. Analyzing changes required.

**Comment by mehuljpatel** [comment]
Thanks Anton for the review and patch !!
All these macros should ideally generate not more than 32 bit number as ppc64 instruction. In the existing list, I checked the biggest is 63 << 26 which is hitting biggest number but still within 32 bit number range. Probably warning is because the magic numbers are not type casted to unsigned int. So we are good with the code now. However, to catch any hand coding errors in future, we should code macros to generate a 64 bit number and have a check that higher 32 bits are zeros and then drop them to be only 32 bit number. If higher 32 bit non-zero, its a bug.

**Comment by antonblanchard** [comment]
Good points. I've changed to using unsigned int modifiers instead of unsigned long. Look better?

**Comment by mehuljpatel** [comment]
Sounds good. As a first step we will make it solid by making the magic number unsigned int. Thanks !

**Pull request merged**
